apiVersion: {{ default "apps/v1" .Values.kubeMeta.deploymentApiVersion }}
kind: Deployment
metadata:
  name: {{ include "clamav.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "clamav.name" . }}
    helm.sh/chart: {{ include "clamav.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "clamav.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "clamav.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.image.digest }}
          image: "{{ .Values.image.name }}@{{ .Values.image.digest }}"
          {{- else }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
{{- if .Values.freshclamConfig }}
          - name: FRESHCLAM_CONF_FILE
            value: "/etc/clamav/user_conf/freshclam.conf"
{{- end }}
{{- if .Values.clamdConfig }}
          - name: CLAMD_CONF_FILE
            value: "/etc/clamav/user_conf/clamd.conf"
{{- end }}
          volumeMounts:
{{- if .Values.freshclamConfig }}
          - name: freshclam-config-volume
            mountPath: /etc/clamav/user_conf
{{- end }}
          ports:
            - name: clamavport
              containerPort: 3310
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: clamavport
            initialDelaySeconds: 300
          readinessProbe:
            tcpSocket:
              port: clamavport
            initialDelaySeconds: 300
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- if .Values.freshclamConfig }}
      volumes:
        - name: freshclam-config-volume
          projected:
            sources:
              - configMap:
                  name: {{ include "clamav.fullname" . }}-freshclam
                  items:
                  - key: freshclam.conf
                    path: freshclam.conf
                  - key: clamd.conf
                    path: clamd.conf
{{- end }}
{{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
